name: Mushmallow CI
run-name: ${{ github.actor }} is running CI at ${{ github.ref_name }}
on: [push]
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install python3.11 python3.11-venv
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: make check
